package edu.rice.comp504.model.strategy;

/**
 * Enum for strategy.
 */
public enum Strategy {
    CHANGECOLORSTRATEGY,
    CHANGESIZESTRATEGY,
    RANDOMVELOCITYSTRATEGY,
    NULLSTRATEGY,
    ROTATINGSTRATEGY,
    SHAKINGSTRATEGY,
    STRAIGHTSTRATEGY,
    REVERSEVELOCITYSTRATEGY,
    CHANGEMASSSTRATEGY,
    RANDOMWALKSTRATEGY,
    RANDOMLOCATIONSTRATEGY,
    SWINGSTRATEGY,
    SUDDENSTOPSTRATEGY
}
